version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: veiculos
      MYSQL_USER: fiap
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    container_name: gerenciamento-veiculos-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/veiculos
      SPRING_DATASOURCE_USERNAME: fiap
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  mysql-data:
